{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-json",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-3.4.0.jar",
          "url": "spring-boot-starter-json-3.4.0.jar",
          "size": 4745,
          "sha512": "b729c815602ade2bae60345b1e642e72705d1a4b0cbf09d27005f6e4b59d8aba6393446e8d98b6b671a4563b7c1bd1f18c4133bc706b099685dbc114cf93bc54",
          "sha256": "c59d27fd47f166f875edc3c888e8f60b8fdbb79e343fc50d4caa2b104cdbbddd",
          "sha1": "b817379dd7629234dbacd52a7d5a6b11f95d8d67",
          "md5": "7c97a433e0ab2db5870292f244606744"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-3.4.0.jar",
          "url": "spring-boot-starter-json-3.4.0.jar",
          "size": 4745,
          "sha512": "b729c815602ade2bae60345b1e642e72705d1a4b0cbf09d27005f6e4b59d8aba6393446e8d98b6b671a4563b7c1bd1f18c4133bc706b099685dbc114cf93bc54",
          "sha256": "c59d27fd47f166f875edc3c888e8f60b8fdbb79e343fc50d4caa2b104cdbbddd",
          "sha1": "b817379dd7629234dbacd52a7d5a6b11f95d8d67",
          "md5": "7c97a433e0ab2db5870292f244606744"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.4.0-javadoc.jar",
          "url": "spring-boot-starter-json-3.4.0-javadoc.jar",
          "size": 4745,
          "sha512": "1daa04e3b841cc0e1084ca3d1973635126d2b87553979568233f20fec885330fb93b4d8b9966c69ff6c2244ef2f7c480bb7ef9dc42e73395b9323d59c5201ca7",
          "sha256": "4ebbe1384fae2331d3406ab2ecb945eb2c11354a989e2d933de6da9b793f0d50",
          "sha1": "b1c16c4d6ad643c1f5a8a83f7f6467c6c4bb7803",
          "md5": "4ef0a11e316e6600655188e7bc2de821"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.4.0-sources.jar",
          "url": "spring-boot-starter-json-3.4.0-sources.jar",
          "size": 4745,
          "sha512": "31c85f9da2f972d502f39d51d0e1f4d12febc40fd9f9b103ebdc7308c0ecc1529aaa84e999cc2e4bf96299ca103c1985dec92eb198d59e1ab853b832cd99d591",
          "sha256": "26c228a871939b67826e474bdc5867617bf06a7f6fb3a3a1d5d970ad830feed6",
          "sha1": "d5a1e032b4e87434d83c0cffddd63f638c376f23",
          "md5": "19d9e0bade748016e0be3d1bad20d39f"
        }
      ]
    }
  ]
}
