{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-expression",
    "version": "6.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-6.2.0.jar",
          "url": "spring-expression-6.2.0.jar",
          "size": 317542,
          "sha512": "2f03fc807d28ee60d24e057eff2157d9a28824e745267110fab7a32d73c839e9b2e856ca16903502d57ae91469d67573d61be28876371d26a06db54b09b6ef8a",
          "sha256": "37cfc1fe8ca22bb789c20aac6b90e09f2b0ea73085f3271ae61cf12cdb7e8876",
          "sha1": "07e92dcd147157641446081db281e9437d8f4dcd",
          "md5": "2ca26c773ce712adbd566db897080b98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-6.2.0.jar",
          "url": "spring-expression-6.2.0.jar",
          "size": 317542,
          "sha512": "2f03fc807d28ee60d24e057eff2157d9a28824e745267110fab7a32d73c839e9b2e856ca16903502d57ae91469d67573d61be28876371d26a06db54b09b6ef8a",
          "sha256": "37cfc1fe8ca22bb789c20aac6b90e09f2b0ea73085f3271ae61cf12cdb7e8876",
          "sha1": "07e92dcd147157641446081db281e9437d8f4dcd",
          "md5": "2ca26c773ce712adbd566db897080b98"
        }
      ]
    }
  ]
}
