{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.2.0.jar",
          "url": "spring-webmvc-6.2.0.jar",
          "size": 1086127,
          "sha512": "0a2385ed72e852861b59f1710e5c3e8447cae26600a51ee3a08ccb67ac32303956b8b1a35555e953c2bf5c5049d6ac4cfe052c040c3b4e018d882b5fcce5df2a",
          "sha256": "6d7a0687d7e3c05fa80d0bb1f636095c8a2fbea8eb99d89a403bd96133387425",
          "sha1": "2eddfeb4d7a12b1ed301bc07abc7e73bca94c2e9",
          "md5": "6912d1bd500823a55e74f5cbc7f1d51b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.2.0.jar",
          "url": "spring-webmvc-6.2.0.jar",
          "size": 1086127,
          "sha512": "0a2385ed72e852861b59f1710e5c3e8447cae26600a51ee3a08ccb67ac32303956b8b1a35555e953c2bf5c5049d6ac4cfe052c040c3b4e018d882b5fcce5df2a",
          "sha256": "6d7a0687d7e3c05fa80d0bb1f636095c8a2fbea8eb99d89a403bd96133387425",
          "sha1": "2eddfeb4d7a12b1ed301bc07abc7e73bca94c2e9",
          "md5": "6912d1bd500823a55e74f5cbc7f1d51b"
        }
      ]
    }
  ]
}
