{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.4.0.jar",
          "url": "spring-boot-3.4.0.jar",
          "size": 1758784,
          "sha512": "dc282eda3c40d86930097bd02fb546c81248e3a6a26ce62f3f6d99764d231ed49f19416884c54e33ef5a5c8c7114319ed85654e249e8bb5721734c54934b202c",
          "sha256": "dea6332c2fa49ce2c724c78e3e57e41417dab50c82f1ccb5bfb22cc993290609",
          "sha1": "cbc6c54cc6958a5e24872025e0d6ff0c87ed3594",
          "md5": "0844399f80f5c0ec027d31a0e0659f8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.4.0.jar",
          "url": "spring-boot-3.4.0.jar",
          "size": 1758784,
          "sha512": "dc282eda3c40d86930097bd02fb546c81248e3a6a26ce62f3f6d99764d231ed49f19416884c54e33ef5a5c8c7114319ed85654e249e8bb5721734c54934b202c",
          "sha256": "dea6332c2fa49ce2c724c78e3e57e41417dab50c82f1ccb5bfb22cc993290609",
          "sha1": "cbc6c54cc6958a5e24872025e0d6ff0c87ed3594",
          "md5": "0844399f80f5c0ec027d31a0e0659f8f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.4.0-javadoc.jar",
          "url": "spring-boot-3.4.0-javadoc.jar",
          "size": 2463243,
          "sha512": "c1e06a875328d2dfd76c8502aa4b0d94b99738b8debe1585da4f54477ba8e9d6607fb0e0f478a7cf5875c3a94d1801aa4c8ddcc333a11f5325b854e18f769390",
          "sha256": "f973df9aa6638bd71a3d1505fb0ae76141f0f85618d50b8688ae0ea13af700f1",
          "sha1": "2808be4d55c6a4217c702d3c1578403491362972",
          "md5": "7a4d1e60385523a7750750e2880a6b91"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.4.0-sources.jar",
          "url": "spring-boot-3.4.0-sources.jar",
          "size": 1182719,
          "sha512": "e6872a1ba05d04782ceb43b0d8b16f6f99912880a7ecf12fa114e78b69f9a70d0e01ddc261cc09f50ac5dea70de9e9ca4f3e37c7cd12b0db4d74972fbd2b6c19",
          "sha256": "ecbae00dd484a44402de93729065692aa851c5cf267de1a31cde0a533a9b07a9",
          "sha1": "857385850f071422302efa077c4b3ac3855ef7ac",
          "md5": "b154e9b40bd27d517d8dc58e3cf0f0a8"
        }
      ]
    }
  ]
}
