{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-autoconfigure",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.4.0.jar",
          "url": "spring-boot-autoconfigure-3.4.0.jar",
          "size": 2000642,
          "sha512": "249b52eb44450716be95a058d98a56b6ec6043757885bbe00e86e7648dca75225b5073c694e1791e9207bae9cc4c07bfe98b95c48b9e43861a42691f55467690",
          "sha256": "525aa88505399c6ccfddfe295b313d55a259ed5e8d5890a3568485c074f98414",
          "sha1": "2cf78b01be25952c96cb8ee60b4b0562b3a136f2",
          "md5": "97d5bb981579f7f1ccf31550618e9bb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.4.0.jar",
          "url": "spring-boot-autoconfigure-3.4.0.jar",
          "size": 2000642,
          "sha512": "249b52eb44450716be95a058d98a56b6ec6043757885bbe00e86e7648dca75225b5073c694e1791e9207bae9cc4c07bfe98b95c48b9e43861a42691f55467690",
          "sha256": "525aa88505399c6ccfddfe295b313d55a259ed5e8d5890a3568485c074f98414",
          "sha1": "2cf78b01be25952c96cb8ee60b4b0562b3a136f2",
          "md5": "97d5bb981579f7f1ccf31550618e9bb6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.4.0-javadoc.jar",
          "url": "spring-boot-autoconfigure-3.4.0-javadoc.jar",
          "size": 3104123,
          "sha512": "b01ac5aa339f1fe1e69d46b66b60750bd54aa81d80d2c14dcea9ccad3c31c0df88e985043fd1008baaff8cd2652b32bdbce0b70262e1d30c9fb23fd983934719",
          "sha256": "d30fdb32514eaeb8cd165a535877759ca555400c9b9071c22add6d431be1f278",
          "sha1": "ff7c3de4dc924b3252297a25d7d69741f76cdc13",
          "md5": "ca8cce717931caddbb0f301fca4f0ed5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.4.0-sources.jar",
          "url": "spring-boot-autoconfigure-3.4.0-sources.jar",
          "size": 1152140,
          "sha512": "fa938eef530a0b05b7e8c2a927fbb79bfff04d1041015bdfad87dfe8ce9f2ab70ddf3dc3e6320468a265e65fca3a7d04ebed39760af98fe687da6397060cdbff",
          "sha256": "29d9d3b7707b657002df78e5d22a9a1cc5136ae8f5697796114e18d656d079a7",
          "sha1": "fd257d3fbc820de6634b5ba7429c560835c7beb2",
          "md5": "03543c38753cf302461c89a4479d8b99"
        }
      ]
    }
  ]
}
