{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.datatype",
    "module": "jackson-datatype-jdk8",
    "version": "2.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jdk8-2.18.1.jar",
          "url": "jackson-datatype-jdk8-2.18.1.jar",
          "size": 35144,
          "sha512": "f2547382fdbc3b6c13016036255154dfe4c98c14a28011ff559c09ad01eef75190c5f360ab296a372b061805cccc1923d43d42c8a085106b2d4de68551fb6d77",
          "sha256": "c2b85dc869405ae17bb04043c703388afe84f550a0c1077d9b09aae965f34c6a",
          "sha1": "4b75bdbaf3670cf3998fa2826bfcdbc4092bbd0f",
          "md5": "ee730dbe423c52b382ef9bced7e3030"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jdk8-2.18.1.jar",
          "url": "jackson-datatype-jdk8-2.18.1.jar",
          "size": 35144,
          "sha512": "f2547382fdbc3b6c13016036255154dfe4c98c14a28011ff559c09ad01eef75190c5f360ab296a372b061805cccc1923d43d42c8a085106b2d4de68551fb6d77",
          "sha256": "c2b85dc869405ae17bb04043c703388afe84f550a0c1077d9b09aae965f34c6a",
          "sha1": "4b75bdbaf3670cf3998fa2826bfcdbc4092bbd0f",
          "md5": "ee730dbe423c52b382ef9bced7e3030"
        }
      ]
    }
  ]
}
