{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.33"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.33"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.33"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.4.0.jar",
          "url": "spring-boot-starter-tomcat-3.4.0.jar",
          "size": 4790,
          "sha512": "7770f288f967ec35316408b24f817dd7b7143cca5afd69fb60c9aa5a4656656c65eac132ad1904c120e425fc51a2e3e088dc632bbe7166a0fcc137b7ffc6c1c2",
          "sha256": "42c1ea37d9de923535d1d15a470576dae308a070f43c249f044d61100f175349",
          "sha1": "90a4cb855aa6fab8da0a3831d8fff5e5a9093d6a",
          "md5": "27fc97f2ebc0bf04c5e237f9195d2c7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.33"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.33"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.33"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.4.0.jar",
          "url": "spring-boot-starter-tomcat-3.4.0.jar",
          "size": 4790,
          "sha512": "7770f288f967ec35316408b24f817dd7b7143cca5afd69fb60c9aa5a4656656c65eac132ad1904c120e425fc51a2e3e088dc632bbe7166a0fcc137b7ffc6c1c2",
          "sha256": "42c1ea37d9de923535d1d15a470576dae308a070f43c249f044d61100f175349",
          "sha1": "90a4cb855aa6fab8da0a3831d8fff5e5a9093d6a",
          "md5": "27fc97f2ebc0bf04c5e237f9195d2c7d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.4.0-javadoc.jar",
          "url": "spring-boot-starter-tomcat-3.4.0-javadoc.jar",
          "size": 4790,
          "sha512": "3567ac45b19b5fdf9bad31b7e8d72591454a5c6cc83a3108ac79cf3772d4b56b44bf3858f4f741888689ea9c4dd0300717bfc063b0b311a1bab92e28c3af1774",
          "sha256": "1cff2ff55703fc57dc03867d63377126ba26922c8f8c2edeee5c29c9ead2a4b8",
          "sha1": "25ca3c09cb2dfd0e0e7d283b7e7deb52548a12bc",
          "md5": "52f8739806a15150d0e278a9b883415c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.4.0-sources.jar",
          "url": "spring-boot-starter-tomcat-3.4.0-sources.jar",
          "size": 4790,
          "sha512": "3567ac45b19b5fdf9bad31b7e8d72591454a5c6cc83a3108ac79cf3772d4b56b44bf3858f4f741888689ea9c4dd0300717bfc063b0b311a1bab92e28c3af1774",
          "sha256": "1cff2ff55703fc57dc03867d63377126ba26922c8f8c2edeee5c29c9ead2a4b8",
          "sha1": "25ca3c09cb2dfd0e0e7d283b7e7deb52548a12bc",
          "md5": "52f8739806a15150d0e278a9b883415c"
        }
      ]
    }
  ]
}
