{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-web",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.4.0.jar",
          "url": "spring-boot-starter-web-3.4.0.jar",
          "size": 4801,
          "sha512": "22e12456e77438edd3948cdd1f6bcd379a3b71abe5db9a7ab1f25729a9e5a2c07d2033e5cca6b763578e78a89f9ded10ff37e0a999154cd5c4a88b7b84a5c1df",
          "sha256": "c146295531ed279a7bef0885c3392e05475d86168c9f010ed57c322f1d1ead0a",
          "sha1": "005447a62dc3dee3eadf2def23314e0db4c81bb3",
          "md5": "dc3217199b54debc6f22fde1551ae047"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.4.0.jar",
          "url": "spring-boot-starter-web-3.4.0.jar",
          "size": 4801,
          "sha512": "22e12456e77438edd3948cdd1f6bcd379a3b71abe5db9a7ab1f25729a9e5a2c07d2033e5cca6b763578e78a89f9ded10ff37e0a999154cd5c4a88b7b84a5c1df",
          "sha256": "c146295531ed279a7bef0885c3392e05475d86168c9f010ed57c322f1d1ead0a",
          "sha1": "005447a62dc3dee3eadf2def23314e0db4c81bb3",
          "md5": "dc3217199b54debc6f22fde1551ae047"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.4.0-javadoc.jar",
          "url": "spring-boot-starter-web-3.4.0-javadoc.jar",
          "size": 4801,
          "sha512": "8d4fec4a270273d05e1478cd45b735ba1caf06a04be3df238b2bcf630fb2017f5dc41f9e95c84bf3f8f992793c504c93b69b9ebb349a2375c5a74daac12d4fe1",
          "sha256": "edb4fa24dd800bc18a84dcf6b182b7bfd2671ace5b660ea8206c8668cb69a1cd",
          "sha1": "6ea637c03e4cac6bf43350144fe32dd29c11ff82",
          "md5": "6fdabd23ccdd70980654f6a460a314d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.4.0-sources.jar",
          "url": "spring-boot-starter-web-3.4.0-sources.jar",
          "size": 4801,
          "sha512": "8d4fec4a270273d05e1478cd45b735ba1caf06a04be3df238b2bcf630fb2017f5dc41f9e95c84bf3f8f992793c504c93b69b9ebb349a2375c5a74daac12d4fe1",
          "sha256": "edb4fa24dd800bc18a84dcf6b182b7bfd2671ace5b660ea8206c8668cb69a1cd",
          "sha1": "6ea637c03e4cac6bf43350144fe32dd29c11ff82",
          "md5": "6fdabd23ccdd70980654f6a460a314d5"
        }
      ]
    }
  ]
}
