{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.4.0.jar",
          "url": "spring-boot-starter-3.4.0.jar",
          "size": 4766,
          "sha512": "0b02a590da997b27c3e5b010e62877acafc2dc9ce0133a77ef531d6a24a8ec85d778a8e188cfadcfc1549a6f23ade63008beec612786526e4309853fb63977ef",
          "sha256": "535d33ec08f2f1a41c6233f4ba20ed5ffbfa277f74dfc983b488f6d0a82e7e95",
          "sha1": "81b6241291e468e5654a4df26ee8fb35c2879bbc",
          "md5": "c7fcbfa645e2c94f420681e48d8112db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.4.0.jar",
          "url": "spring-boot-starter-3.4.0.jar",
          "size": 4766,
          "sha512": "0b02a590da997b27c3e5b010e62877acafc2dc9ce0133a77ef531d6a24a8ec85d778a8e188cfadcfc1549a6f23ade63008beec612786526e4309853fb63977ef",
          "sha256": "535d33ec08f2f1a41c6233f4ba20ed5ffbfa277f74dfc983b488f6d0a82e7e95",
          "sha1": "81b6241291e468e5654a4df26ee8fb35c2879bbc",
          "md5": "c7fcbfa645e2c94f420681e48d8112db"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.4.0-javadoc.jar",
          "url": "spring-boot-starter-3.4.0-javadoc.jar",
          "size": 4766,
          "sha512": "5cc37c7884066a621ff929ba95a0a2009e8f1525fe60572fd534eabe4f115dc493651c732f25141217ea5b45028d68bbf8bad34930dfaf2b8d3288a0da26464b",
          "sha256": "0c236f9d0949ec49c4a6c57472fdcd12f00dedbe44b2aea23a084c4ef410fb2f",
          "sha1": "24bba68ee6d4c5096892261a81862946d90d432c",
          "md5": "39bea9f0ec0f59e5083965411629f460"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.4.0-sources.jar",
          "url": "spring-boot-starter-3.4.0-sources.jar",
          "size": 4766,
          "sha512": "5cc37c7884066a621ff929ba95a0a2009e8f1525fe60572fd534eabe4f115dc493651c732f25141217ea5b45028d68bbf8bad34930dfaf2b8d3288a0da26464b",
          "sha256": "0c236f9d0949ec49c4a6c57472fdcd12f00dedbe44b2aea23a084c4ef410fb2f",
          "sha1": "24bba68ee6d4c5096892261a81862946d90d432c",
          "md5": "39bea9f0ec0f59e5083965411629f460"
        }
      ]
    }
  ]
}
