{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-web",
    "version": "6.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-6.2.0.jar",
          "url": "spring-web-6.2.0.jar",
          "size": 2080882,
          "sha512": "041b6fd463fd1815f70f4232211b565462e12b8dabca36cb464abcc342d9dc20ddb4873e5f8ab63018387111430f847b79a3f6486aab1ad2c7e2526281489cff",
          "sha256": "24bd75b1049104699e4f57f3a70fc2ba41943d667d5d1a3b24ed1b70c3582020",
          "sha1": "e1b702476fe83b2354baf88b8179f71c53fbbfae",
          "md5": "40a7afc7ff39473eefe3e5117d6a3331"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-6.2.0.jar",
          "url": "spring-web-6.2.0.jar",
          "size": 2080882,
          "sha512": "041b6fd463fd1815f70f4232211b565462e12b8dabca36cb464abcc342d9dc20ddb4873e5f8ab63018387111430f847b79a3f6486aab1ad2c7e2526281489cff",
          "sha256": "24bd75b1049104699e4f57f3a70fc2ba41943d667d5d1a3b24ed1b70c3582020",
          "sha1": "e1b702476fe83b2354baf88b8179f71c53fbbfae",
          "md5": "40a7afc7ff39473eefe3e5117d6a3331"
        }
      ]
    }
  ]
}
