{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aop",
    "version": "6.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-6.2.0.jar",
          "url": "spring-aop-6.2.0.jar",
          "size": 418340,
          "sha512": "ceab313204d9797e6534e1c7084a84ae29ad841874056f1fc596e28633fd4e4a14cba38a847187c3d692ec60c8b5d9f39f245d72fb14604d5b4b6e219555ca29",
          "sha256": "fe84f18bdefb3ad4f993357d31e61613bb55f348d7ea69ec1ca968b3240b3b08",
          "sha1": "999012dfb56640f7babdf4f6c55b3f59c1596f3f",
          "md5": "b9c9beb994c71a780072080b05dba8fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-6.2.0.jar",
          "url": "spring-aop-6.2.0.jar",
          "size": 418340,
          "sha512": "ceab313204d9797e6534e1c7084a84ae29ad841874056f1fc596e28633fd4e4a14cba38a847187c3d692ec60c8b5d9f39f245d72fb14604d5b4b6e219555ca29",
          "sha256": "fe84f18bdefb3ad4f993357d31e61613bb55f348d7ea69ec1ca968b3240b3b08",
          "sha1": "999012dfb56640f7babdf4f6c55b3f59c1596f3f",
          "md5": "b9c9beb994c71a780072080b05dba8fa"
        }
      ]
    }
  ]
}
