{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-logging",
    "version": "3.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.12"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.4.0.jar",
          "url": "spring-boot-starter-logging-3.4.0.jar",
          "size": 4755,
          "sha512": "06368ed62aff90a72f7ce51b905cfd837a00d9bbec0a1073e0e33747dbd57f0951ffcdb7d5fbb2c99634e198657587b996738ee992a9002b50b8f85611b4d41c",
          "sha256": "3a5196a0651b8d94cc0f2a227331153d4a24d76b22cfea70d966842f127f1108",
          "sha1": "10d953f63139bf05ca8bee79272aadac745e297e",
          "md5": "aee0bcff591c5a223b15b312c3a00151"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.12"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.4.0.jar",
          "url": "spring-boot-starter-logging-3.4.0.jar",
          "size": 4755,
          "sha512": "06368ed62aff90a72f7ce51b905cfd837a00d9bbec0a1073e0e33747dbd57f0951ffcdb7d5fbb2c99634e198657587b996738ee992a9002b50b8f85611b4d41c",
          "sha256": "3a5196a0651b8d94cc0f2a227331153d4a24d76b22cfea70d966842f127f1108",
          "sha1": "10d953f63139bf05ca8bee79272aadac745e297e",
          "md5": "aee0bcff591c5a223b15b312c3a00151"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.4.0-javadoc.jar",
          "url": "spring-boot-starter-logging-3.4.0-javadoc.jar",
          "size": 4755,
          "sha512": "53efab0d254538cf1d5f1a498131f5dea8da2d923bf9d3ce2175fa0b180b60d0db0b3e8ae6ed0cc82cb1ef68a9130e0d6d53eeb7d51d43c343c5c1813e5a77c2",
          "sha256": "aea0a8a98dcdfc6edda52f854c1c9c9f47a227e62c65f573d98e32c0531642a3",
          "sha1": "41dff5363bb6f6dd97a8b0ee7d67eb21dc9f4591",
          "md5": "06ce80c1330b8c1ff71330db3efa2ed0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.4.0-sources.jar",
          "url": "spring-boot-starter-logging-3.4.0-sources.jar",
          "size": 4755,
          "sha512": "53efab0d254538cf1d5f1a498131f5dea8da2d923bf9d3ce2175fa0b180b60d0db0b3e8ae6ed0cc82cb1ef68a9130e0d6d53eeb7d51d43c343c5c1813e5a77c2",
          "sha256": "aea0a8a98dcdfc6edda52f854c1c9c9f47a227e62c65f573d98e32c0531642a3",
          "sha1": "41dff5363bb6f6dd97a8b0ee7d67eb21dc9f4591",
          "md5": "06ce80c1330b8c1ff71330db3efa2ed0"
        }
      ]
    }
  ]
}
