{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-beans",
    "version": "6.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-6.2.0.jar",
          "url": "spring-beans-6.2.0.jar",
          "size": 875125,
          "sha512": "523a083ceaaa3f043ef9714ef04b754c627a1c04943d89522cb2f31708ba8618c5b3b10926ef00fef5de2632cb89c218dd2eb3aff6e0dff594872c0b802be5f6",
          "sha256": "33adf77b49236f2966c9cec7eb5a1aea8ade81d7ada80c36d91bbf89d3298e15",
          "sha1": "0972694ca3c2f44d64d55429dfcc6ca2dfa9fddf",
          "md5": "0d67557d2c1408525c72172dde199978"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-6.2.0.jar",
          "url": "spring-beans-6.2.0.jar",
          "size": 875125,
          "sha512": "523a083ceaaa3f043ef9714ef04b754c627a1c04943d89522cb2f31708ba8618c5b3b10926ef00fef5de2632cb89c218dd2eb3aff6e0dff594872c0b802be5f6",
          "sha256": "33adf77b49236f2966c9cec7eb5a1aea8ade81d7ada80c36d91bbf89d3298e15",
          "sha1": "0972694ca3c2f44d64d55429dfcc6ca2dfa9fddf",
          "md5": "0d67557d2c1408525c72172dde199978"
        }
      ]
    }
  ]
}
